# Generated by Django 5.2.9 on 2026-01-22 14:30

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("paperless", "0004_applicationconfiguration_barcode_asn_prefix_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationconfiguration",
            name="barcode_enable_metadata",
            field=models.BooleanField(
                null=True,
                verbose_name="Enables metadata barcode extraction",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="barcode_metadata_auto_create",
            field=models.JSONField(
                null=True,
                verbose_name="Sets which metadata properties to auto-create",
            ),
        ),
        migrations.AddField(
            model_name="applicationconfiguration",
            name="barcode_metadata_mapping",
            field=models.JSONField(
                null=True,
                verbose_name="Sets the metadata barcode regex mapping",
            ),
        ),
    ]
